### ISSUE TITLE
can gobackup exclude subdirectories ? 

### ISSUE THREAD

**Issue by mind029** [huacnlee/gobackup#23]
Thanks gobackup author，Can gobackup exclude subdirectories ? such as include the path `/home/wwwroot/test.cn`, exclude the path `home/wwwroot/test.cn/upload` , the following is my configuration file：

```yml
 ## 源码备份
  sourceBackup:
    # 备份打包
    compress_with:
      # 压缩方式
      type: tgz
    # 存储
    store_with:
      # 存储到oss上
      ........
    # 文件备份
    archive:
      # 需要备份的文件、文件夹
      includes:
        - /home/wwwroot/test.cn
      excludes:
        - /home/wwwroot/test.cn/upload

```
