### ISSUE TITLE
阿里云 同样的 access_id 和 secret 在 carrierwave-aliyun 能用，gobackup 用报错

### ISSUE THREAD

**Issue by huobazi** [huacnlee/gobackup#36]
```
2019/01/01 16:18:52 oss: service returned error: StatusCode=400, ErrorCode=InvalidArgument, ErrorMessage=Authorization header is invalid., RequestId=5C0B226C2FF16CF75093E762
```
gobackup.yml:
```
# gobackup config example
# -----------------------
# Put this file in follow place:
# ~/.gobackup/gobackup.yml or /etc/gobackup/gobackup.yml
models:
  yfxs:
    compress_with:
      type: tgz
    store_with:
      type: oss
      keep: 10
      endpoint: oss-cn-hangzhou-internal.aliyuncs.com
      bucket: aaa
      accessKeyID: aaa
      accessKeySecret: aaa
      path: /aaa
    databases:
      aaa_production:
        type: postgresql
        host: localhost
        port: 5432
        database: aaa
        username: aaa
        password: aaa
    archive:
      includes:
        - /application/app/aaa/shared/etc/nginx.conf
        - /etc/nginx/nginx.conf
        - /etc/redis/redis.conf
                                                                                                                        30,0-1        All
```
