### ISSUE TITLE
备份压缩文件本地缓存自动清理或者设置最大文件数进行滚动清理

### ISSUE THREAD

**Issue by songjiayang** [huacnlee/gobackup#58]
### gobackup.yml  配置：

```
models:
  example:
    compress_with:
      type: tgz
    store_with:
      type: oss
      max_retries: 5
      timeout: 300
      threads: 1 (1 .. 100)
    archive:
      includes:
        - /home/git/.ssh/
        - /etc/nginx/nginx.conf
        - /etc/nginx/conf.d
      excludes:
        - /home/ubuntu/.ssh/known_hosts
        - /etc/logrotate.d/syslog
```

### 现象： 

设置 cronjob 每日备份，gobackup 会在 `/tmp/gobackup` 目录下生成对应每日备份文件的压缩文件。我设置的对象存储的保存策略，但本地备份的压缩文件不断积累，需要手动清理。

###  需求：

1. 新增配置，支持备份对象存储后本地文件直接清除。
2. 支持本地缓存文件的最大数量，支持滚动清理。
