### ISSUE TITLE
How to dump once and save to multiple places?

### ISSUE THREAD

**Issue by xgrei** [huacnlee/gobackup#59]
I want to backup mysql, and the yml config just has 1 `store_with` i can set.

How to dump once and save to `local` and `s3`?

I don't want to set 2 models in config file.

Thank you.

**Comment by zoeeer** [comment]
I guess you can set `local dump -> s3` as your 2nd model

**Comment by huacnlee** [comment]
```yml
models:
  local_backup:
    compress_with:
      type: tgz
    databases:
      dummy_test:
        type: mysql
        host: localhost
        port: 3306
        database: dummy_test
        username: root
        password: 123456
    store_with:
      type: local
      path: /data/backups
  s3_backup:
    archive:
      includes:
        - /data/backup_to_s3
    store_with:
      type: s3
      bucket: gobackup-test
      region: ap-southeast-1
      path: backups
      access_key_id: 
      secret_access_key: 
```

And then run:

```bash
gobackup perform local_backup 
mkdir -p /data/backup_to_s3 && mv  /data/backups/*.tar.gz /data/backup_to_s3
gobackup perform s3_backup
```
