### ISSUE TITLE
Postgres asks for password every time

### ISSUE THREAD

**Issue by greatghoul** [huacnlee/gobackup#7]
This is my configuration file.

```yml
models:
  yizaoyiwan:
    compress_with:
      type: tgz
    store_with:
      type: local
      path: /home/deploy/.gobackup/backups
    databases:
      yizaoyiwan:
        type: postgresql
        database: yizaoyiwan
        host: localhost
        username: postgres
        password: xxxx
    archive:
      includes:
        - /home/deploy/.bashrc
```

if I manually set PGPASSWORD in my `~/.bashrc`, it works and continues to perform the backup.

https://github.com/huacnlee/gobackup/blob/master/database/postgresql.go#L77
